### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by znh05** [R-a-s-c-a-l/Thinkpad-X13-Gen1-Hackintosh#1]
你好
感谢分享。
使用后发现雷电转DP外接显示器睡眠后无法唤醒外接显示器。
且外接显示器只能到2k分辨率
（显示器为4k，且win下都正常）。
望能提供建议，再次感谢。
如方便，请加我 q：1405597866

**Comment by R-a-s-c-a-l** [comment]
4K 需要改DVMT 雷电的话我没放任何相关的补丁 😂

**Comment by R-a-s-c-a-l** [comment]
你把雷电控制器的路径发我一下 因为这本子不是我的 EFI也是我帮别人做的顺便放到了我GitHub仓库里

**Comment by znh05** [comment]
感谢回复，具体怎么看路径呢，是在win下么看么。电脑在单位，要后天去单位才能看😅

R-a-s-c-a-l ***@***.***> 于2021年9月15日周三 下午3:15写道：

**Comment by znh05** [comment]
是类似于这种么[image: image.png]

sir li ***@***.***> 于2021年9月15日周三 下午10:05写道：

**Comment by R-a-s-c-a-l** [comment]
win 下设备管理器 系统设备 Thunderbolt 控制器 属性 详细信息 BIOS设备名称 或者 位置路径

**Comment by znh05** [comment]
看着也许有用的都拷贝了一下😅
设备描述
Thunderbolt(TM) Controller - 15BF
设备实例路径
PCI\VEN_8086&DEV_15BF&SUBSYS_22AE17AA&REV_01\9128704296B3020000
位置路径
PCIROOT(0)#PCI(1C04)#PCI(0000)#PCI(0000)#PCI(0000)
ACPI(_SB_)#ACPI(PCI0)#ACPI(RP05)#ACPI(PXSX)#PCI(0000)#PCI(0000)
配置id
oem37.inf:PCI\VEN_8086&DEV_15BF&CC_0880,TbtBusDrv_Device.NT
物理设备对象名称
\Device\NTPNP_PCI0024
父系
PCI\VEN_8086&DEV_15C0&SUBSYS_22AE17AA&REV_01\9128704296B3020000
硬件id
PCI\VEN_8086&DEV_15BF&SUBSYS_22AE17AA&REV_01
PCI\VEN_8086&DEV_15BF&SUBSYS_22AE17AA
PCI\VEN_8086&DEV_15BF&CC_088000
PCI\VEN_8086&DEV_15BF&CC_0880

R-a-s-c-a-l ***@***.***> 于2021年9月16日周四 下午12:17写道：

**Comment by znh05** [comment]
你好
请教一下，我看github上你更新了两个aml文件，我覆盖了一下，上次提到的问题好像没什么变化，是更新的这个问题么

sir li ***@***.***> 于2021年9月17日周五 上午10:28写道：

**Comment by znh05** [comment]
[image: 3F49D1534E8A16E493E68CBFEF6BF19B.png]你好，修改后雷电外接显示器完美4k，再次感谢🙏

sir li ***@***.***> 于2021年9月22日周三 上午10:34写道：

**Comment by znh05** [comment]
你好
请教一下，最近需要用到麦克风，发现机器内置麦克风无法正常工作（耳机孔插带mic耳机正常），尝试相关alcid也无法解决，目前alcid为11，有什么建议么
